### ISSUE TITLE
`--verbose` does not display http log information when given a direct URL

### ISSUE THREAD

**Issue by mefellows** [pact-foundation/pact-provider-verifier#71]
Whilst debugging an issue for the Pact .NET provider, I wanted to see the HTTP details due to an authentication failure.

When given a direct URL however, no extra HTTP debugging info is present.

Example with direct URL:
```
✗ PACT_BROKER_BASE_URL=  pact-provider-verifier --verbose --provider-base-url http://localhost:9000 https://testdemo.pactflow.io/pacts/provider/pactflow-example-provider-dotnet/consumer/pactflow-example-consumer-dotnet/pact-version/ae47e9fed1b12954ff5306fa24bd758cdc1e8346
Error reading file from https://testdemo.pactflow.io/pacts/provider/pactflow-example-provider-dotnet/consumer/pactflow-example-consumer-dotnet/pact-version/ae47e9fed1b12954ff5306fa24bd758cdc1e8346
HTTP request failed: status=401 /opt/pact/lib/vendor/ruby/2.2.0/gems/pact-support-1.16.7/lib/pact/consumer_contract/pact_file.rb:71:in `block in get_remote_with_retry'
/opt/pact/lib/vendor/ruby/2.2.0/gems/pact-support-1.16.7/lib/pact/consumer_contract/pact_file.rb:60:in `times'
/opt/pact/lib/vendor/ruby/2.2.0/gems/pact-support-1.16.7/lib/pact/consumer_contract/pact_file.rb:60:in `get_remote_with_retry'
/opt/pact/lib/vendor/ruby/2.2.0/gems/pact-support-1.16.7/lib/pact/consumer_contract/pact_file.rb:41:in `render_pact'
/opt/pact/lib/vendor/ruby/2.2.0/gems/pact-support-1.16.7/lib/pact/consumer_contract/pact_file.rb:22:in `read'
/opt/pact/lib/vendor/ruby/2.2.0/gems/pact-1.57.0/lib/pact/provider/pact_source.rb:17:in `pact_json'
/opt/pact/lib/vendor/ruby/2.2.0/gems/pact-1.57.0/lib/pact/provider/pact_spec_runner.rb:123:in `collect'
/opt/pact/lib/vendor/ruby/2.2.0/gems/pact-1.57.0/lib/pact/provider/pact_spec_runner.rb:123:in `pact_jsons'
/opt/pact/lib/vendor/ruby/2.2.0/gems/pact-1.57.0/lib/pact/provider/pact_spec_runner.rb:80:in `configure_rspec'
/opt/pact/lib/vendor/ruby/2.2.0/gems/pact-1.57.0/lib/pact/provider/pact_spec_runner.rb:33:in `run'
/opt/pact/lib/vendor/ruby/2.2.0/gems/pact-1.57.0/lib/pact/cli/run_pact_verification.rb:70:in `run_with_pact_uri_object'
/opt/pact/lib/vendor/ruby/2.2.0/gems/pact-1.57.0/lib/pact/cli/run_pact_verification.rb:51:in `run_specs'
/opt/pact/lib/vendor/ruby/2.2.0/gems/pact-1.57.0/lib/pact/cli/run_pact_verification.rb:21:in `call'
/opt/pact/lib/vendor/ruby/2.2.0/gems/pact-1.57.0/lib/pact/cli/run_pact_verification.rb:13:in `call'
/opt/pact/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.35.0/lib/pact/provider_verifier/app.rb:177:in `verify_pact'
/opt/pact/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.35.0/lib/pact/provider_verifier/app.rb:50:in `block in pacts_pass_verification?'
/opt/pact/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.35.0/lib/pact/provider_verifier/app.rb:49:in `collect'
/opt/pact/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.35.0/lib/pact/provider_verifier/app.rb:49:in `pacts_pass_verification?'
/opt/pact/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.35.0/lib/pact/provider_verifier/app.rb:41:in `call'
/opt/pact/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.35.0/lib/pact/provider_verifier/app.rb:34:in `call'
/opt/pact/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.35.0/lib/pact/provider_verifier/cli/verify.rb:48:in `verify'
/opt/pact/lib/vendor/ruby/2.2.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
/opt/pact/lib/vendor/ruby/2.2.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
/opt/pact/lib/vendor/ruby/2.2.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
/opt/pact/lib/vendor/ruby/2.2.0/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
/opt/pact/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.35.0/lib/pact/provider_verifier/cli/custom_thor.rb:17:in `start'
/opt/pact/lib/app/pact-provider-verifier.rb:33:in `<main>'
/opt/pact/lib/vendor/ruby/2.2.0/gems/pact-support-1.16.7/lib/pact/consumer_contract/pact_file.rb:71:in `block in get_remote_with_retry': HTTP request failed: status=401 (Pact::PactFile::HttpError)
	from /opt/pact/lib/vendor/ruby/2.2.0/gems/pact-support-1.16.7/lib/pact/consumer_contract/pact_file.rb:60:in `times'
	from /opt/pact/lib/vendor/ruby/2.2.0/gems/pact-support-1.16.7/lib/pact/consumer_contract/pact_file.rb:60:in `get_remote_with_retry'
	from /opt/pact/lib/vendor/ruby/2.2.0/gems/pact-support-1.16.7/lib/pact/consumer_contract/pact_file.rb:41:in `render_pact'
	from /opt/pact/lib/vendor/ruby/2.2.0/gems/pact-support-1.16.7/lib/pact/consumer_contract/pact_file.rb:22:in `read'
	from /opt/pact/lib/vendor/ruby/2.2.0/gems/pact-1.57.0/lib/pact/provider/pact_source.rb:17:in `pact_json'
	from /opt/pact/lib/vendor/ruby/2.2.0/gems/pact-1.57.0/lib/pact/provider/pact_spec_runner.rb:123:in `collect'
	from /opt/pact/lib/vendor/ruby/2.2.0/gems/pact-1.57.0/lib/pact/provider/pact_spec_runner.rb:123:in `pact_jsons'
	from /opt/pact/lib/vendor/ruby/2.2.0/gems/pact-1.57.0/lib/pact/provider/pact_spec_runner.rb:80:in `configure_rspec'
	from /opt/pact/lib/vendor/ruby/2.2.0/gems/pact-1.57.0/lib/pact/provider/pact_spec_runner.rb:33:in `run'
	from /opt/pact/lib/vendor/ruby/2.2.0/gems/pact-1.57.0/lib/pact/cli/run_pact_verification.rb:70:in `run_with_pact_uri_object'
	from /opt/pact/lib/vendor/ruby/2.2.0/gems/pact-1.57.0/lib/pact/cli/run_pact_verification.rb:51:in `run_specs'
	from /opt/pact/lib/vendor/ruby/2.2.0/gems/pact-1.57.0/lib/pact/cli/run_pact_verification.rb:21:in `call'
	from /opt/pact/lib/vendor/ruby/2.2.0/gems/pact-1.57.0/lib/pact/cli/run_pact_verification.rb:13:in `call'
	from /opt/pact/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.35.0/lib/pact/provider_verifier/app.rb:177:in `verify_pact'
	from /opt/pact/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.35.0/lib/pact/provider_verifier/app.rb:50:in `block in pacts_pass_verification?'
	from /opt/pact/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.35.0/lib/pact/provider_verifier/app.rb:49:in `collect'
	from /opt/pact/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.35.0/lib/pact/provider_verifier/app.rb:49:in `pacts_pass_verification?'
	from /opt/pact/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.35.0/lib/pact/provider_verifier/app.rb:41:in `call'
	from /opt/pact/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.35.0/lib/pact/provider_verifier/app.rb:34:in `call'
	from /opt/pact/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.35.0/lib/pact/provider_verifier/cli/verify.rb:48:in `verify'
	from /opt/pact/lib/vendor/ruby/2.2.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
	from /opt/pact/lib/vendor/ruby/2.2.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
	from /opt/pact/lib/vendor/ruby/2.2.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
	from /opt/pact/lib/vendor/ruby/2.2.0/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
	from /opt/pact/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.35.0/lib/pact/provider_verifier/cli/custom_thor.rb:17:in `start'
	from /opt/pact/lib/app/pact-provider-verifier.rb:33:in `<main>'
```

Example when you pass in the broker dettails:
```
➜  pactflow-example-provider-net git:(master) ✗ pact-provider-verifier --verbose --provider-base-url http://localhost:9000 --consumer-version-tag prod --enable-pending --provider pactflow-example-provider
opening connection to testdemo.pactflow.io:443...
opened
starting SSL for testdemo.pactflow.io:443...
SSL established
<- "GET / HTTP/1.1\r\nAccept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3\r\nAccept: application/hal+json\r\nUser-Agent: Ruby\r\nHost: testdemo.pactflow.io\r\n\r\n"
-> "HTTP/1.1 401 Unauthorized\r\n"
-> "Date: Fri, 23 Jul 2021 11:34:07 GMT\r\n"
-> "Content-Type: text/plain\r\n"
-> "Content-Length: 88\r\n"
-> "Connection: keep-alive\r\n"
-> "Vary: Accept\r\n"
-> "X-Pact-Broker-Version: 2.80.0\r\n"
-> "X-Pact-Broker-Git-Sha: 0a7a25c6\r\n"
-> "X-Pactflow-Git-Sha: bc2551074\r\n"
-> "X-Content-Type-Options: nosniff\r\n"
-> "Strict-Transport-Security: max-age=63072000; includeSubDomains; preload\r\n"
-> "X-Request-Id: 9495f9a44b0ed9c9b20904d2780a8bca\r\n"
-> "\r\n"
reading 88 bytes...
-> "Unauthorized. Please see https://docs.pactflow.io/docs/login-help for more information.\n"
read 88 bytes
Conn keep-alive
/opt/pact/lib/vendor/ruby/2.2.0/gems/pact-1.57.0/lib/pact/hal/entity.rb:102:in `assert_success!': Error retrieving https://testdemo.pactflow.io status=401 Unauthorized. Please see https://docs.pactflow.io/docs/login-help for more information. (Pact::Hal::ErrorResponseReturned)
	from /opt/pact/lib/vendor/ruby/2.2.0/gems/pact-1.57.0/lib/pact/pact_broker/fetch_pact_uris_for_ver
...
```

**Comment by bethesque** [comment]
Hm. The direct URL will be the old code, which won't have the verbose flag passed through to it. See if I can wire it up.

**Comment by bethesque** [comment]
Fixed in https://github.com/pact-foundation/pact-support/commit/3288b818942f460cb7909f22687787a2b77f5e37

New pact-support has just been released. Standalone should be out soon.

**Comment by mefellows** [comment]
Awesome, thank you Beth!
